id: P002938
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01511
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས། ༡ ༼༡༠༽
  author: ''
  volumes:
    34d2f8c91506419fb7c5ca51b553b65d:
      image_group_id: I4705
      title: ''
      volume_number: 1
      total_pages: 143
